version: '3.5'

services:
  nginx:
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - "./volumes/certs/letsencrypt:/etc/nginx/certs:rw"

  docker-gen:
    volumes:
      - "./volumes/certs/letsencrypt:/etc/nginx/certs:rw"

  nginx-letsencrypt:
    image: "jrcs/letsencrypt-nginx-proxy-companion:v1.12"
    container_name: nginx-letsencrypt
    restart: "unless-stopped"
    env_file:
      - .env
    volumes:
      - "./volumes/conf.d:/etc/nginx/conf.d"
      - "./volumes/vhost.d:/etc/nginx/vhost.d"
      - "./volumes/html:/usr/share/nginx/html"
      - "./volumes/certs/letsencrypt:/etc/nginx/certs:rw"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      NGINX_DOCKER_GEN_CONTAINER: "docker-gen"
      NGINX_PROXY_CONTAINER: "nginx"
      # DEBUG: "true"
    links:
      - rsyslog
    logging:
      driver: syslog
      options:
        tag: "nginx-letsencrypt"
        syslog-address: "tcp://localhost:5555"
